routes/web.php
<?php

use App\Http\Controllers\UnidadeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return redirect('/dashboard');
});

Route::group([
    'prefix' => 'acessogov',
    'namespace' => 'App\Http\Controllers\Acessogov',
], function () {
    Route::get('/autorizacao', 'LoginAcessoGov@autorizacao')->name('acessogov.autorizacao');
    Route::get('/tokenacesso', 'LoginAcessoGov@tokenAcesso')->name('acessogov.tokenacesso');
});

Route::group([
    'middleware' => array_merge(
        (array) config('backpack.base.web_middleware', 'web'),
        (array) config('backpack.base.middleware_key', 'admin')
    ),
], function () { // custom admin routes

    Route::get('/change-unidade',[UnidadeController::class,'setDefault'])->name('unidade.change');

}); // this should be the absolute last line of this file

app/Models/SiadsExtPatrim.php
<?php

namespace App\Models;

use Backpack\CRUD\app\Models\Traits\CrudTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class SiadsExtPatrim extends Model
{
    use CrudTrait;
    use HasFactory;

    protected $connection = 'pgsql2';
    protected $table = 'siads_ext_patrim';
    protected $primaryKey = 'id';


    public function getOrgaoAttribute()
    {
        return $this->it_co_orgao;
    }

    public function getUnidadeAttribute()
    {
        return str_pad($this->it_co_ug, 6, '0', STR_PAD_LEFT);
    }

    public function getGestaoAttribute()
    {
        return str_pad($this->it_co_gestao, 5, '0', STR_PAD_LEFT);
    }

    public function getUorgAttribute()
    {
        return $this->it_co_uorg;
    }

    public function getContaContabilAttribute()
    {
        return $this->it_co_conta_contabil;
    }

    public function getNumeroPatrimonialAntigoAttribute()
    {
        return $this->it_nu_patrimonial_ant;
    }

    public function getNumeroPatrimonialAttribute()
    {
        return $this->it_nu_patrimonial;
    }

    public function getDataTombamentoAttribute()
    {
        return ($this->it_da_tombamento !== '0') ? date('Y-m-d', strtotime($this->it_da_tombamento)) : null;
    }

    public function getCodigoMaterialAttribute()
    {
        return $this->it_co_item_material;
    }

    public function getNomeMaterialAttribute()
    {
        return $this->it_no_material;
    }

    public function getDescricaoComplementarAttribute()
    {
        return $this->it_tx_descricao_complementar;
    }

    public function getMarcaAttribute()
    {
        return $this->it_no_marca;
    }

    public function getModeloAttribute()
    {
        return $this->it_no_modelo;
    }

    public function getSerieAttribute()
    {
        return $this->it_nu_serie;
    }

    public function getFabricanteAttribute()
    {
        return $this->it_no_fabricante;
    }

    public function getProcessoAttribute()
    {
        return $this->it_nu_processo;
    }

    public function getCodigoTerceirosAttribute()
    {
        return $this->it_co_terceiros;
    }

    public function getValorInicialBemAttribute()
    {
        return $this->it_va_inicial_bem;
    }

    public function getValorBemAttribute()
    {
        return $this->it_va_bem;
    }

    public function getValorDepreciadoAttribute()
    {
        return $this->it_va_bem_depre;
    }

    public function getValorLiquidoAttribute()
    {
        return $this->it_va_liq_bem;
    }

    public function getValorDoacaoVendaAttribute()
    {
        return $this->it_va_doacao_venda;
    }

    public function getCodigoTipoBemAttribute()
    {
        return $this->it_co_tipo_bem;
    }

    public function getNomeTipoBemAttribute()
    {
        return $this->it_no_tipo_bem;
    }

    public function getCodigoSituacaoAttribute()
    {
        return $this->it_co_situacao;
    }

    public function getNomeSituacaoAttribute()
    {
        return $this->it_no_situacao;
    }

    public function getCodigoDestinacaoAttribute()
    {
        return $this->it_co_destinacao;
    }

    public function getNomeDestinacaoAttribute()
    {
        return $this->it_no_destinacao;
    }

    public function getCpfResponsavelAttribute()
    {
        return $this->it_nu_cpf_responsavel;
    }

    public function getNomeResponsavelAttribute()
    {
        return $this->it_no_responsavel;
    }

    public function getCpfResponsavelUorgAttribute()
    {
        return $this->it_co_resp_uorg;
    }

    public function getNomeResponsavelUorgAttribute()
    {
        return $this->it_no_resp_uorg;
    }

}

resources/views/patrim/pdf-table.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Tabela de Dados</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 11px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
        }
        th {
            background-color: #f2f2f2;
            text-align: left;
        }
    </style>
</head>
<body>
<header>
    <img src="{{ public_path('img/report.png') }}" alt="Header Image">
</header>
<h2>Patrimônios</h2>
<table>
    <thead>
    <tr>
        @foreach($titles as $k=>$title)
            @if($k<6)
                <th>{{$title}}</th>
            @endif
        @endforeach
    </tr>
    </thead>
    <tbody>
    @foreach ($results as $current=>$result)
        {{ $callback($total,$current) }}
        <tr>
            @foreach($names as $k=>$name)
                @if($k<6)
                    <td>{{$result->$name}}</td>
                @endif
            @endforeach
        </tr>
    @endforeach
    </tbody>
</table>
</body>
</html>

resources/views/patrim/pdf.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Formulário de Dados</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }
        .container {
            width: 100%;
            margin: 0 auto;
        }
        .form-section {
            margin-bottom: 20px;
        }
        .form-section h3 {
            margin-bottom: 10px;
            color: #333;
        }
        .form-section p {
            margin: 0;
            padding: 5px 0;
            color: #555;
        }
    </style>
</head>
<body>
<header>
    <img src="{{ public_path('img/report.png') }}" alt="Header Image">
</header>
<div class="container">

    <h3>Formulário de Patrimônios</h3>
    @foreach ($results as $current=>$result)
        {{ $callback($total,$current) }}
        <div class="form-section">
            <table>
                <tr>
                    <td>
                        <p><strong>UG:</strong> {{ $result->uasg }}</p>
                        <p><strong>UORG:</strong> {{ $result->uorg }}</p>
                        <p><strong>Gestão:</strong> {{ $result->gestao }}</p>
                        <p><strong>Conta:</strong> {{ $result->conta }}</p>
                        <p><strong>Número Patrimonial:</strong> {{ $result->numero_patrimonial }}</p>
                        <p><strong>Descrição do material:</strong> {{ $result->descricao_material }}</p>
                        <p><strong>Valor:</strong> {{ $result->valor }}</p>
                    </td>
                    <td>&nbsp;</td>
                    <td>
                        <p><strong>Data do tombamento:</strong> {{ $result->data_tombamento }}</p>
                        <p><strong>Situação:</strong> {{ $result->situacao }}</p>
                        <p><strong>Destinação:</strong> {{ $result->destinacao }}</p>
                        <p><strong>Endereço:</strong> {{ $result->endereco }}</p>
                        <p><strong>Responsável:</strong> {{ $result->responsavel }}</p>
                        <p><strong>Forma de aquisição:</strong> {{ $result->forma_aquisicao }}</p>
                        <p><strong>Garantia de Compra:</strong> {{ $result->contrato_garantia_compra }}</p>
                    </td>
                </tr>
            </table>


        </div>
        <hr>
    @endforeach
</div>
</body>
</html>